routes/web.php
<?php

use Illuminate\Support\Facades\Route;
use App\Http\Controllers\EmployeeController;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

// Route::get('/', function () {
//     return view('employee.index');
// });


Route::resource('employees', EmployeeController::class);
Route::delete('employees/delete/{id}', [EmployeeController::class, 'delete'])->name("employees.delete");

app/Models/Employee.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class Employee extends Model
{
    use HasFactory;

    protected $fillable = [
        'name'
    ];

    public function address(){
        return $this->hasOne(Address::class);
    }

    public function mobileNumbers(){
        return $this->hasMany(MobileNumber::class);
    }

    public function whatsappNumbers(){
        return $this->hasMany(WhatsappNumber::class);
    }

    public function emailAddresses(){
        return $this->hasMany(EmailAddress::class);
    }
}

app/Http/Controllers/EmployeeController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use App\Models\Address;
use App\Models\EmailAddress;
use App\Models\Employee;
use App\Models\MobileNumber;
use App\Models\WhatsappNumber;
use Illuminate\Support\Facades\DB;

class EmployeeController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        // return view('employees.index');
        $employees = Employee::all();
        return view("employees.index", compact([
            'employees'
        ]));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('employees.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {

        $employee = Employee::create([
            'name' => $request['name']
        ]);

        $address = Address::create([
            'employee_id' => $employee->id,
            'address_1' => $request['address_1'],
            'address_2' => $request['address_2'],
            'location' => $request['location'],
            'pin_code' => $request['pin_code'],
            'postal_area' => $request['postal_area'],
            'taluka' => $request['taluka'],
            'suburb' => $request['suburb'],
            'east_west' => $request['east_west'],
            'city' => $request['city'],
            'district' => $request['district'],
            'state' => $request['state'],
            'country' => $request['country']
        ]);

        $mobileArray = $request['mobile'];
        // dd($mobileArray);
        for($i=0;$i<count($mobileArray);$i++){
            if($mobileArray[$i]['checked'] == "true"){
                $is_primary = "1";
            }else{
                $is_primary = "0";
            }
            $mobile = MobileNumber::create([
                'employee_id' => $employee->id,
                'mobile_number' => $mobileArray[$i]['value'],
                'is_primary' => $is_primary
            ]);
        }

        $whatsappArray = $request['whatsapp'];
        for($i=0;$i<count($whatsappArray);$i++){
            if($whatsappArray[$i]['checked'] == "true"){
                $is_primary = "1";
            }else{
                $is_primary = "0";
            }
            $whatsapp = WhatsappNumber::create([
                'employee_id' => $employee->id,
                'whatsapp_number' => $whatsappArray[$i]['value'],
                'is_primary' => $is_primary
            ]);
        }

        $emailArray = $request['email'];
        for($i=0;$i<count($emailArray);$i++){
            if($emailArray[$i]['checked'] == "true"){
                $is_primary = "1";
            }else{
                $is_primary = "0";
            }
            $whatsapp = EmailAddress::create([
                'employee_id' => $employee->id,
                'email_address' => $emailArray[$i]['value'],
                'is_primary' => $is_primary
            ]);
        }

        return "success";

        // DB::insert("INSERT INTO employee (name) VALUES (?)", [$request['name']]);
        // $id = DB::select("SELECT LAST_INSERT_ID()");

        // DB::insert("INSERT INTO address (employee_id, address_1, address_2, location, pin_code, postal_area, taluka, suburb, east_west, city, district, state, country) VALUES (?,?,?,?,?,?,?,?,?,?,?,?,?)", [$request['employee_id'], $request['address_1'], $request['address_2'], $request['location'], $request['pin_code'], $request['postal_area'], $request['taluka'], $request['suburb'], $request['east_west'], $request['city'], $request['district'], $request['state'], $request['country'],]);


        // return $request['name'];
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        // dd($id);
        $employee = Employee::find($id);
        $address = $employee->address;
        $mobileArray = $employee->mobileNumbers;
        $whatsappArray = $employee->whatsappNumbers;
        $emailArray = $employee->emailAddresses;
        
        return view("employees.show", compact([
            'employee',
            'address',
            'mobileArray',
            'whatsappArray',
            'emailArray',
        ]));
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $employee = Employee::find($id);
        $address = $employee->address;
        $mobileArray = $employee->mobileNumbers;
        $whatsappArray = $employee->whatsappNumbers;
        $emailArray = $employee->emailAddresses;
        
        return view("employees.edit", compact([
            'employee',
            'address',
            'mobileArray',
            'whatsappArray',
            'emailArray',
        ]));

    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {

        DB::table('employees')->where('id', $id)->delete();

        $employee = Employee::create([
            'name' => $request['name']
        ]);

        $address = Address::create([
            'employee_id' => $employee->id,
            'address_1' => $request['address_1'],
            'address_2' => $request['address_2'],
            'location' => $request['location'],
            'pin_code' => $request['pin_code'],
            'postal_area' => $request['postal_area'],
            'taluka' => $request['taluka'],
            'suburb' => $request['suburb'],
            'east_west' => $request['east_west'],
            'city' => $request['city'],
            'district' => $request['district'],
            'state' => $request['state'],
            'country' => $request['country']
        ]);

        $mobileArray = $request['mobile'];
        // dd($mobileArray);
        for($i=0;$i<count($mobileArray);$i++){
            if($mobileArray[$i]['checked'] == "true"){
                $is_primary = "1";
            }else{
                $is_primary = "0";
            }
            $mobile = MobileNumber::create([
                'employee_id' => $employee->id,
                'mobile_number' => $mobileArray[$i]['value'],
                'is_primary' => $is_primary
            ]);
        }

        $whatsappArray = $request['whatsapp'];
        for($i=0;$i<count($whatsappArray);$i++){
            if($whatsappArray[$i]['checked'] == "true"){
                $is_primary = "1";
            }else{
                $is_primary = "0";
            }
            $whatsapp = WhatsappNumber::create([
                'employee_id' => $employee->id,
                'whatsapp_number' => $whatsappArray[$i]['value'],
                'is_primary' => $is_primary
            ]);
        }

        $emailArray = $request['email'];
        for($i=0;$i<count($emailArray);$i++){
            if($emailArray[$i]['checked'] == "true"){
                $is_primary = "1";
            }else{
                $is_primary = "0";
            }
            $whatsapp = EmailAddress::create([
                'employee_id' => $employee->id,
                'email_address' => $emailArray[$i]['value'],
                'is_primary' => $is_primary
            ]);
        }

        return "success";
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        DB::table('employees')->where('id', $id)->delete();

        return redirect(route('employees.index'));
    }
}

resources/views/employees/index.blade.php
<!doctype html>
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- Bootstrap CSS -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-+0n0xVW2eSR5OomGNYDnhzAbDsOXxcvSN1TPprVMTNDbiYZCxYbOOl7+AMvyTG2x" crossorigin="anonymous">

    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/4.5.2/css/bootstrap.css">
    <link rel="stylesheet" href="https://cdn.datatables.net/1.10.25/css/dataTables.bootstrap4.min.css">

    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.css" integrity="sha512-5A8nwdMOWrSz20fDsjczgUidUBR8liPYU+WymTZP1lmY9G6Oc7HlZv156XqnsgNUzTyMefFTcsFH/tnJE/+xBg==" crossorigin="anonymous" referrerpolicy="no-referrer" />

    <link href="{{ asset('css/app.css') }}" rel="stylesheet">

    <title>Hello, world!</title>
  </head>
  <body>
      <div class="container mt-5">

        <table id="employee_table" class="table table-striped table-bordered" style="width:100%">
            <thead>
                <tr>
                    <th>Sr No.</th>
                    <th>Name</th>
                    <th>Operation</th>
                </tr>
            </thead>
            <tbody>
@foreach ($employees as $employee)
                <tr>
                    <td></td>
                    <td><?= $employee->name ?></td>
                    <td>
                        <div class="view-card d-inline-block mr-2">
                            <form action="{{ route('employees.show',$employee->id) }}">
                                <button class="btn btn-secondary view-btn" type="submit">
                                    <div class="fa fa-eye"></div>
                                </button>
                            </form>
                        </div>
                        <div class="edit-card d-inline-block mr-2">
                            <form action="{{ route('employees.edit',$employee->id) }}">
                                <button class="btn btn-primary edit-btn" type="submit">
                                    <div class="fa fa-pencil"></div>
                                </button>
                            </form>
                        </div>
                        <div class="delete-card d-inline-block mr-2">
                            <form action="{{ route('employees.destroy',$employee->id) }}" method="POST">
                                @csrf
                                @method('DELETE')
                                <button class="btn btn-danger delete-btn" type="submit">
                                    <div class="fa fa-trash"></div>
                                </button>
                            </form>
                        </div>
                    </td>
                </tr>
@endforeach
            </tbody>
        </table>

      </div>
  </body>

    <script src="https://code.jquery.com/jquery-3.5.1.js"></script>
    <script src="https://cdn.datatables.net/1.10.25/js/jquery.dataTables.min.js"></script>
    <script src="https://cdn.datatables.net/1.10.25/js/dataTables.bootstrap4.min.js"></script>
    <script>
    $(document).ready(function() {
        $('#employee_table').DataTable({
            "fnRowCallback" : function(nRow, aData, iDisplayIndex){
                $("td:first", nRow).html(iDisplayIndex +1);
                return nRow;
        },
        'columnDefs': [ {
            'targets': [2], // column index (start from 0)
            'orderable': false, // set orderable false for selected columns
        }]
        });
    } );
    </script>
</html>